// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNbtkE5uh6R-AflUTUPrkj5ZvyXGwxBdQ',
    appId: '1:755741762456:web:df48acfd0bffd9b76741ed',
    messagingSenderId: '755741762456',
    projectId: 'domex-9718a',
    authDomain: 'domex-9718a.firebaseapp.com',
    storageBucket: 'domex-9718a.firebasestorage.app',
    measurementId: 'G-88B1XTGVF0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvW3-bviPQxLQxvfLwCJzQdTQvp-fDg-E',
    appId: '1:755741762456:android:e0a77990fd0c63156741ed',
    messagingSenderId: '755741762456',
    projectId: 'domex-9718a',
    storageBucket: 'domex-9718a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFiHSpjhxPnbWdBuU0geLZTzqz7ACcZIQ',
    appId: '1:755741762456:ios:03b02784849146f26741ed',
    messagingSenderId: '755741762456',
    projectId: 'domex-9718a',
    storageBucket: 'domex-9718a.firebasestorage.app',
    iosBundleId: 'com.example.controle99',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFiHSpjhxPnbWdBuU0geLZTzqz7ACcZIQ',
    appId: '1:755741762456:ios:03b02784849146f26741ed',
    messagingSenderId: '755741762456',
    projectId: 'domex-9718a',
    storageBucket: 'domex-9718a.firebasestorage.app',
    iosBundleId: 'com.example.controle99',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCNbtkE5uh6R-AflUTUPrkj5ZvyXGwxBdQ',
    appId: '1:755741762456:web:d504929bff621d3f6741ed',
    messagingSenderId: '755741762456',
    projectId: 'domex-9718a',
    authDomain: 'domex-9718a.firebaseapp.com',
    storageBucket: 'domex-9718a.firebasestorage.app',
    measurementId: 'G-B5QS62FTTQ',
  );
}
